apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: cloudo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:latest
          args:
            - azurite
            - --skipApiVersionCheck
            - --blobHost
            - 0.0.0.0
            - --queueHost
            - 0.0.0.0
            - --tableHost
            - 0.0.0.0
            - --location
            - /data
          ports:
            - containerPort: 10000
              name: blob
            - containerPort: 10001
              name: queue
            - containerPort: 10002
              name: table
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: cloudo
spec:
  selector:
    app: azurite
  ports:
    - name: blob
      port: 10000
      targetPort: blob
    - name: queue
      port: 10001
      targetPort: queue
    - name: table
      port: 10002
      targetPort: table
