apiVersion: v1
kind: Secret
metadata:
  name: cloudo-secrets
stringData:
  AzureWebJobsStorage: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1"
  CLOUDO_SECRET_KEY: "local"
  SESSION_SECRET: "local-session-secret"
  APPROVAL_SECRET: "local-approval-secret"
  SLACK_TOKEN_DEFAULT: ""
  SLACK_CHANNEL_DEFAULT: "#cloudo-test"
  JSM_API_KEY_DEFAULT: ""
  GITHUB_TOKEN: ""
  GOOGLE_CLIENT_ID: ""
  FUNCTION_KEY: ""
