apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudo-config
data:
  API_PREFIX: "/api"
  CLOUDO_ENVIRONMENT: "prod"
  CLOUDO_ENVIRONMENT_SHORT: "p"
  FEATURE_DEV: "false"
  WEBSITES_PORT: "80"
  GITHUB_REPO: "pagopa/payments-cloudo"
  GITHUB_BRANCH: "main"
  GITHUB_PATH_PREFIX: "src/runbooks"
  LOGS_BLOB_CONTAINER: "runbook-logs"
  FASTAPI_NOTIFICATION_CONCURRENCY: "4"
  FASTAPI_NOTIFICATION_BATCH_SIZE: "4"
  FASTAPI_NOTIFICATION_VISIBILITY_TIMEOUT: "300"
  FASTAPI_QUEUE_CONCURRENCY: "4"
  FASTAPI_QUEUE_BATCH_SIZE: "4"
  FASTAPI_QUEUE_VISIBILITY_TIMEOUT: "3600"
  AKS_INTEGRATION_ENABLED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudo-worker-local-config
data:
  QUEUE_NAME: "local"
  WORKER_CAPABILITY: "local"
  WEBSITE_SITE_NAME: "worker-local"
  ORCHESTRATOR_URL: "http://orchestrator/api/workers/register"
  RECEIVER_URL: "http://orchestrator/api/receiver"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudo-worker-alert-config
data:
  QUEUE_NAME: "alert"
  WORKER_CAPABILITY: "alert"
  WEBSITE_SITE_NAME: "worker-alert"
  ORCHESTRATOR_URL: "http://orchestrator/api/workers/register"
  RECEIVER_URL: "http://orchestrator/api/receiver"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudo-ui-config
data:
  API_URL: "http://orchestrator/api"
  ORCHESTRATOR_URL: "http://orchestrator"
