apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudo
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  - storage-bootstrap-job.yaml
  - orchestrator-deployment.yaml
  - orchestrator-service.yaml
  - worker-local-deployment.yaml
  - worker-local-service.yaml
  - worker-local-hpa.yaml
  - worker-alert-deployment.yaml
  - worker-alert-service.yaml
  - worker-alert-hpa.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - ingress.yaml
