apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudo-ui
  template:
    metadata:
      labels:
        app: cloudo-ui
    spec:
      containers:
        - name: cloudo-ui
          image: ghcr.io/pagopa/cloudo-ui:0.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudo-ui-config
                  key: API_URL
            - name: ORCHESTRATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: cloudo-ui-config
                  key: ORCHESTRATOR_URL
            - name: CLOUDO_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudo-secrets
                  key: CLOUDO_SECRET_KEY
            - name: FUNCTION_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudo-secrets
                  key: FUNCTION_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cloudo-secrets
                  key: GOOGLE_CLIENT_ID
            - name: FEATURE_DEV
              valueFrom:
                configMapKeyRef:
                  name: cloudo-config
                  key: FEATURE_DEV
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
