{{- if .Values.azurite.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: {{ include "cloudo.namespace" . }}
  labels:
    {{- include "cloudo.labels" . | nindent 4 }}
    app.kubernetes.io/component: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
        {{- include "cloudo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: azurite
    spec:
      containers:
        - name: azurite
          image: {{ .Values.azurite.image }}
          command:
            - azurite
            - --blobHost
            - "0.0.0.0"
            - --queueHost
            - "0.0.0.0"
            - --tableHost
            - "0.0.0.0"
            - --loose
          ports:
            - containerPort: 10000
              name: blob
            - containerPort: 10001
              name: queue
            - containerPort: 10002
              name: table
          resources:
            {{- toYaml .Values.azurite.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: azurite
  namespace: {{ include "cloudo.namespace" . }}
  labels:
    {{- include "cloudo.labels" . | nindent 4 }}
    app.kubernetes.io/component: azurite
spec:
  type: ClusterIP
  selector:
    app: azurite
  ports:
    - name: blob
      port: 10000
      targetPort: blob
    - name: queue
      port: 10001
      targetPort: queue
    - name: table
      port: 10002
      targetPort: table
{{- end }}
