apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: {{ include "cloudo.namespace" . }}
  labels:
    {{- include "cloudo.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
    - name: http
      port: 80
      targetPort: http
