{{- range .Values.workers }}
---
apiVersion: v1
kind: Service
metadata:
  name: worker-{{ .name }}
  namespace: {{ include "cloudo.namespace" $ }}
  labels:
    {{- include "cloudo.labels" $ | nindent 4 }}
    app.kubernetes.io/component: worker-{{ .name }}
spec:
  type: ClusterIP
  selector:
    app: worker-{{ .name }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
